language: node_js
env:
  global:
    - secure: <YOUR_ENCRYPTED_DATA>
node_js:
- '0.10'
before_install:
- npm uninstall psi browser-sync --save-dev
script:
- node ./node_modules/gulp/bin/gulp build --release
after_success:
- git config --global user.name = "Your Name"
- git config --global user.email = "email@example.com"
- node ./node_modules/gulp/bin/gulp deploy --production
