// ImageModel
const SIMILAR_VALUE = 4;
const POSITIVE_NOT_MATCH_COUNT = 8;
const NAGTIVE_MATCH_COUNT = 5;

// Shape
const AROUND_RADIUS = 10;
const SHAPE_SIZE = 50;

module.exports = {
  SIMILAR_VALUE,
  POSITIVE_NOT_MATCH_COUNT,
  NAGTIVE_MATCH_COUNT,
  AROUND_RADIUS,
  SHAPE_SIZE,
}